apiVersion: v1
kind: Service
metadata:
  name: foxfang
  labels:
    app: foxfang
spec:
  type: ClusterIP
  selector:
    app: foxfang
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
