export const browserCoreExamples = [
  "foxfang browser status",
  "foxfang browser start",
  "foxfang browser stop",
  "foxfang browser tabs",
  "foxfang browser open https://example.com",
  "foxfang browser focus abcd1234",
  "foxfang browser close abcd1234",
  "foxfang browser screenshot",
  "foxfang browser screenshot --full-page",
  "foxfang browser screenshot --ref 12",
  "foxfang browser snapshot",
  "foxfang browser snapshot --format aria --limit 200",
  "foxfang browser snapshot --efficient",
  "foxfang browser snapshot --labels",
];

export const browserActionExamples = [
  "foxfang browser navigate https://example.com",
  "foxfang browser resize 1280 720",
  "foxfang browser click 12 --double",
  'foxfang browser type 23 "hello" --submit',
  "foxfang browser press Enter",
  "foxfang browser hover 44",
  "foxfang browser drag 10 11",
  "foxfang browser select 9 OptionA OptionB",
  "foxfang browser upload /tmp/foxfang/uploads/file.pdf",
  'foxfang browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "foxfang browser dialog --accept",
  'foxfang browser wait --text "Done"',
  "foxfang browser evaluate --fn '(el) => el.textContent' --ref 7",
  "foxfang browser console --level error",
  "foxfang browser pdf",
];
